BoxLayout:
    orientation: 'horizontal'
    Button:
        text: 'Genesis'
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            Button:
                text: 'Exodus'
            Button:
                text: 'Leviticus'
            Button:
                text: 'Numbers'
        Button:
            text: 'Deuteronomy'
        Button:
            text: 'John'

